volumes:
  database_data:
    driver: local

secrets:
  db_password:
    environment: DB_PASSWORD
  sendgrid_api_key:
    environment: SENDGRID_API_KEY
  twilio_account_sid:
    environment: TWILIO_ACCOUNT_SID
  twilio_auth_token:
    environment: TWILIO_AUTH_TOKEN

services:
  webserver:
    build:
      context: ./
      dockerfile: docker/webserver/Dockerfile
    restart: on-failure:5
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/api/ping" ]
      interval: 60s
      timeout: 3s
      retries: 3
    environment:
      DB_HOST: "${DB_HOST}"
      DB_NAME: "${DB_NAME}"
      DB_PASSWORD_FILE: /run/secrets/db_password
      DB_USER: "${DB_USER}"
      LOGGER_LOCATION: "${LOGGER_LOCATION}"
      LOGGER_NAME: "${LOGGER_NAME}"
      SENDGRID_API_KEY_FILE: /run/secrets/sendgrid_api_key
      SENDGRID_SENDER_EMAIL: "${SENDGRID_SENDER_EMAIL}"
      SENDGRID_SENDER_NAME: "${SENDGRID_SENDER_NAME}"
      TWILIO_ACCOUNT_SID_FILE: /run/secrets/twilio_account_sid
      TWILIO_AUTH_TOKEN_FILE: /run/secrets/twilio_auth_token
      TWILIO_PHONE_NUMBER: "${TWILIO_PHONE_NUMBER}"
      TWILIO_WHATSAPP_NUMBER: "${TWILIO_WHATSAPP_NUMBER}"
    secrets:
      - db_password
      - sendgrid_api_key
      - twilio_account_sid
      - twilio_auth_token

  database:
    image: postgres:17.4-alpine3.21
    ports:
      - "54321:5432"
    environment:
      POSTGRES_DB: "${DB_NAME}"
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - database_data:/var/lib/postgresql/data/pgdata
    secrets:
      - db_password
